package egl

// ANGLE specific options found in eglext.h
const (
	PLATFORM_ANGLE_ANGLE                   = 0x3202
	PLATFORM_ANGLE_TYPE_ANGLE              = 0x3203
	PLATFORM_ANGLE_MAX_VERSION_MAJOR_ANGLE = 0x3204
	PLATFORM_ANGLE_MAX_VERSION_MINOR_ANGLE = 0x3205
	PLATFORM_ANGLE_TYPE_DEFAULT_ANGLE      = 0x3206

	PLATFORM_ANGLE_TYPE_D3D9_ANGLE            = 0x3207
	PLATFORM_ANGLE_TYPE_D3D11_ANGLE           = 0x3208
	PLATFORM_ANGLE_DEVICE_TYPE_ANGLE          = 0x3209
	PLATFORM_ANGLE_DEVICE_TYPE_HARDWARE_ANGLE = 0x320A
	PLATFORM_ANGLE_DEVICE_TYPE_WARP_ANGLE     = 0x320B

	PLATFORM_ANGLE_TYPE_OPENGL_ANGLE   = 0x320D
	PLATFORM_ANGLE_TYPE_OPENGLES_ANGLE = 0x320E
)
